export default [
  {
    name: 'スペードデッキ',
    cards: [
      { imageUrl: "/sample/card_spade_01.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_spade_02.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_spade_03.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_spade_04.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_spade_05.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_spade_06.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_spade_07.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_spade_08.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_spade_09.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_spade_10.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_spade_11.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_spade_12.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_spade_13.png", backImageUrl: "/sample/card-back.png", time: 4 },
    ],
  },
  {
    name: 'ダイヤデッキ',
    cards: [
      { imageUrl: "/sample/card_diamond_01.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_diamond_02.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_diamond_03.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_diamond_04.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_diamond_05.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_diamond_06.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_diamond_07.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_diamond_08.png", backImageUrl: "/sample/card-back.png", time: 2 },
      { imageUrl: "/sample/card_diamond_09.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_diamond_10.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_diamond_11.png", backImageUrl: "/sample/card-back.png", time: 3 },
      { imageUrl: "/sample/card_diamond_12.png", backImageUrl: "/sample/card-back.png", time: 4 },
      { imageUrl: "/sample/card_diamond_13.png", backImageUrl: "/sample/card-back.png", time: 4 },
    ],
  },
]
